# Generated by Django 4.2.5 on 2023-10-03 12:14

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_usuarios')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('rua', models.CharField(blank=True, max_length=200, verbose_name='Rua')),
                ('numero', models.CharField(blank=True, max_length=10, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=200, verbose_name='Complemento')),
                ('cidade', models.CharField(blank=True, max_length=200, null=True, verbose_name='Cidade')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('estado', models.CharField(blank=True, choices=[('AC', 'ACRE'), ('AL', 'ALAGOAS'), ('AP', 'AMAPÁ'), ('AM', 'AMAZONAS'), ('BA', 'BAHIA'), ('CE', 'CEARÁ'), ('DF', 'DISTRITO FEDERAL'), ('ES', 'ESPÍRITO SANTO'), ('GO', 'GOIÁS'), ('MA', 'MARANHÃO'), ('MT', 'MATO GROSSO'), ('MS', 'MATO GROSSO DO SUL'), ('MG', 'MINAS GERAIS'), ('PA', 'PARÁ'), ('PB', 'PARAÍBA'), ('PR', 'PARANÁ'), ('PE', 'PERNAMBUCO'), ('PI', 'PIAUÍ'), ('RJ', 'RIO DE JANEIRO'), ('RN', 'RIO GRANDE DO NORTE'), ('RS', 'RIO GRANDE DO SUL'), ('RO', 'RONDÔNIA'), ('RR', 'RORAIMA'), ('SC', 'SANTA CATARINA'), ('SP', 'SÃO PAULO'), ('SE', 'SERGIPE'), ('TO', 'TOCANTINS')], max_length=2, null=True, verbose_name='Estado')),
                ('data_criacao', models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Data de Inclusão')),
                ('total_entradas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Entradas')),
                ('total_saidas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Saídas')),
                ('saldo_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Saldo Final')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('P', 'Pagamento'), ('R', 'Recebimento')], default='P', max_length=1, verbose_name='Tipo')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('data_criacao', models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Data de Inclusão')),
            ],
            options={
                'verbose_name': 'Categorias',
                'verbose_name_plural': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='SaldoInicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_inicial', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Inicial')),
                ('data_criacao', models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Data de Inclusão')),
            ],
        ),
        migrations.CreateModel(
            name='Movimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_movimento', models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Data do Movimento')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da operação')),
                ('data_criacao', models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Data de Inclusão')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimentos',
                'verbose_name_plural': 'Movimento',
            },
        ),
    ]
